services:
    _defaults:
        autowire: true
        autoconfigure: true

    Dahovitech\FileManagerBundle\Repository\FileRepository:
        tags: ['doctrine.repository_service']

    Dahovitech\FileManagerBundle\Repository\FolderRepository:
        tags: ['doctrine.repository_service']

    Dahovitech\FileManagerBundle\Service\ThumbnailService:
        alias: file_manager.thumbnail_service

    Dahovitech\FileManagerBundle\Service\MetadataExtractorService:
        alias: file_manager.metadata_extractor

    Dahovitech\FileManagerBundle\Service\FileManagerService:
        arguments:
            $storages:
                local.storage: '@oneup_flysystem.local_storage_filesystem_filesystem'

    Dahovitech\FileManagerBundle\Controller\FileManagerController:
        arguments:
            $storages:
                local.storage: '@oneup_flysystem.local_storage_filesystem_filesystem'